export GOWASP_PATH=/home/bmauer/swdev/packages/GOWASP
#export GOWASP_GSIPATH=/home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install-SLES15
#export GOWASP_BUFRBIN=/home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install-SLES15/bin
export GOWASP_GSIPATH=/home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas
#export GOWASP_BUFRBIN=/home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/Linux/bin
export GOWASP_G5MODS=/home/dao_ops/GEOSadas-5_29_5_SLES15/GEOSadas/install-SLES15/bin/g5_modules.sh
export GEOSPATH1=$GOWASP_GSIPATH
export BASEDIR1=$BASEDIR
source $GOWASP_G5MODS
